name: Keep Render Server Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:        # Allows manual runs too

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          curl -m 10 RENDER_SERVER_URL || echo "Server is down"
