name: Keep Render Server Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server and Check Response
        run: |
          RESPONSE=$(curl -m 10 -s https://wired-new.onrender.com)
          if [[ "$RESPONSE" == *"Welcome to Wired"* ]]; then
            echo "✅ Server is awake and responding correctly."
          else
            echo "⚠️ Server responded but did not return expected output."
            exit 1
